#!/usr/bin/env node
/**
 * `bun run free:check` — a site built from this template cannot bill its owner.
 *
 * The promise: you fork this, you get a live site, and nothing about it can
 * produce an invoice. Not "probably cheap" — no metered resource is reachable
 * at all, so there is no number to watch.
 *
 * That promise is easy to make and easy to break by accident. One binding added
 * to a Function, one fetch to somebody's paid API, and every adopter who pulls
 * the update inherits a bill they never agreed to. This asserts the boundary
 * instead of trusting it, because the person who pays is not the person who
 * merged the change.
 *
 * What is deliberately NOT checked: the adopter's own account. If someone puts
 * this behind a paid Cloudflare plan or buys a domain, that is their
 * infrastructure and their decision (ADR 028). This gate governs what the
 * TEMPLATE ships.
 */
import { readFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/*
 * Cloudflare bindings that meter. KV is absent on purpose: the Fit quota
 * counter is a free-tier key-value pair holding a hashed IP and an integer,
 * and it exists precisely to CAP a cost surface. Everything here either bills
 * per unit or has no free tier worth relying on.
 */
const METERED_BINDINGS = [
  ["Workers AI", /\benv\.AI\b|binding\s*=\s*"AI"|ai\s*=\s*\{/],
  ["Vectorize", /\bVECTORIZE\b|vectorize/i],
  ["D1", /\bD1Database\b|d1_databases/],
  ["R2", /\bR2Bucket\b|r2_buckets/],
  ["Queues", /\bQueue\b\s*[;,)]|queue_producers|queue_consumers/],
  ["Durable Objects", /\bDurableObject\b|durable_objects/],
  ["Hyperdrive", /\bHyperdrive\b|hyperdrive/i],
  ["Browser Rendering", /\bpuppeteer\b|browser_rendering/i],
];

/* A Function reaching a third-party host is the classic cost leak: it looks
   like ordinary code and it spends somebody else's money on every request.
   Same-origin fetches are built from request.url and are not absolute. */
const ABSOLUTE_FETCH = /fetch\(\s*["'`]https?:\/\//;

const failures = [];

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) walk(abs, out);
    else if (/\.(ts|js|mjs)$/.test(entry.name)) out.push(abs);
  }
  return out;
}

// ---------- 1. no real wrangler config is committed ----------
// wrangler.toml carries account ids and live bindings. Only the example ships.
if (existsSync(join(root, "wrangler.toml"))) {
  failures.push(
    "wrangler.toml is committed — it carries account ids and live bindings. Only wrangler.example.toml belongs in the tree",
  );
}

// ---------- 2. no metered binding reachable from a Function ----------
const sources = [...walk(join(root, "functions")), join(root, "wrangler.example.toml")].filter((f) => existsSync(f));

for (const file of sources) {
  const rel = relative(root, file).replace(/\\/g, "/");
  // Generated by build-fit-worker from src/fit/match.ts; it is the matcher,
  // and checking a bundle produces noise rather than signal.
  if (rel.endsWith("_lib/fit-engine.js")) continue;
  const text = readFileSync(file, "utf8");

  for (const [name, pattern] of METERED_BINDINGS) {
    if (pattern.test(text)) {
      failures.push(
        `${rel}: references ${name}, which meters. A site built from this template must not be able to bill its owner — see ADR 028`,
      );
    }
  }
  if (ABSOLUTE_FETCH.test(text)) {
    failures.push(
      `${rel}: fetches an absolute http(s) URL. A Function calling a third-party host spends the adopter's money on every request; same-origin fetches build from request.url`,
    );
  }
}

// ---------- 3. the deploy target is one of the free ones ----------
const generated = join(root, "src", "generated", "content.ts");
if (existsSync(generated)) {
  const target = (readFileSync(generated, "utf8").match(/deployTarget:\s*"([^"]+)"/) || [])[1];
  if (target && !["github-pages", "cloudflare-pages"].includes(target)) {
    failures.push(`deploy target ${target} is not a known free-tier host`);
  }
}

if (failures.length) {
  console.error("check-free: FAILED");
  for (const f of failures) console.error(`  - ${f}`);
  process.exit(1);
}

console.log(
  `check-free: ok (${sources.length} Function sources; no metered binding, no third-party fetch, no committed wrangler.toml)`,
);
